### ISSUE TITLE
[BUG] taxa(), ntips() and rootAge() don't work

### ISSUE THREAD

**Issue by siariazi** [revbayes/revbayes#239] opened 2022-05-01 19:20 UTC
Hello, 

I’m using RevBayes version 1.1.1 on Windows and now trying to reproduce the results of “Simple Diversification Rate Estimation” from here:  [https://revbayes.github.io/tutorials/divrate/simple.html](url)

When I run this line of code:
`taxa <- T.taxa()`

I get this message:
`Error: No function named 'taxa'`

I get the same message for `T.ntips()` and `T.rootAge()` as well.

In addition when I run this line:
`timetree ~ dnBDP(lambda=birth_rate, mu=0.0, rho=rho, rootAge=root_time, samplingStrategy="uniform", condition="survival", taxa=taxa)`

I get this message: 
```
Error:	Argument or label mismatch for function call.
   Provided call:
   dnBDP (RealPos<stochastic> 'lambda',
          Probability<constant> 'mu',
          RealPos<constant> 'rho',
          Natural<constant> 'rootAge',
          String<constant> 'samplingStrategy',
          String<constant> 'condition',
          Natural<constant> 'taxa',
          Natural<constant> 'Clade' )
   Correct usage is:
   dnBirthDeath (RealPos<any> lambda,
                 RealPos<any> mu,
                 Probability<any> rho,
                 RealPos<any> rootAge,
                 String<any> samplingStrategy {valid options: "uniform"|"diversified"},
                 String<any> condition {valid options: "time"|"survival"|"nTaxa"},
                 Taxon[]<any> taxa,
                 Clade[]<any> incompleteClades)
```
Where there is no clade provided in the sample data. 
Are those functions revised and there is a new tutorial covering them?

**Comment by davidcerny** [comment] 2022-07-05 21:37
Hi @siariazi, I unfortunately don't have access to a Windows machine, but I tried – and failed – to reproduce this error using RevBayes 1.1.1 on macOS.

In my experience, the error you describe is often due to the fact that RevBayes distinguishes between a vector of trees of length 1, and a single tree that forms an element of such a vector. In the following example, `T` is actually a vector of trees (as indicated by the square brackets, `[]`), and I get the same error as you:

```
> T <- readTrees("data/primates_tree.nex")
   Attempting to read the contents of file "primates_tree.nex"
   Successfully read file
> type(T)
    TimeTree[]
> taxa <- T.taxa()
   Error:	No function named 'taxa'
```

However, everything works as expected with proper indexing (notice the `[1]` appended to the end of the `readTrees()` call), when we actually extract a single tree from the vector:

```
> T <- readTrees("data/primates_tree.nex")[1]
   Attempting to read the contents of file "primates_tree.nex"
   Successfully read file
> type(T)
   TimeTree
> taxa <- T.taxa()
>
```

Could you please confirm whether the error persists even when you add `[1]` to the `readTrees()` call?

**Comment by bredelings** [comment] 2022-10-04 17:53
I think that @davidcerny is right -- there doesn't seem to be a bug in revbayes.

Before closing this bug, I wonder if we can provide a more helpful error message, since multiple people are having this problem.
- we could print the type of T automatically, to show that it is not a tree?
- we could recommend `T.methods()` to show what methods are available?

**Comment by bredelings** [comment] 2022-10-04 18:03
Currently the error is an exception that is thrown from `FunctionTable::findFunction( )` in `src/revlanguage/workspace/FunctionTable.cpp`.  But we don't have enough information there to give a good error message.

However, this is called from `SyntaxFunctionCall::evaluateContent( )` in `src/revlanguage/parser/SyntaxFunctionCall.cpp`.
>         Function* the_function = mt.getFunction( function_name, args, !dynamic ).clone();
Probably we should create the error message here.

One thing we could do is to 
- 1.first check if there is such a function.
- 2. if there is not, throw an error message mentioning the type of the base variable
- 3. if there is, then clone the function and proceed.

Probably we could change getFunction( ) to return a pointer to the function, and return a null pointer if there isn't any.

**Closed** 2022-10-28 12:52 UTC
