### ISSUE TITLE
[BUG] Checkpoint error encountered when running models with mass extinction components

### ISSUE THREAD

**Issue by mhDu** [revbayes/revbayes#429] opened 2024-02-16 13:09 UTC
**Describe the bug**
When executing models that include mass extinction components with Checkpoint enabled, an error occurs:
`rb(3472,0x119813e00) malloc: *** error for object 0x7ffa9ebc2f40: pointer being freed was not allocated
rb(3472,0x119813e00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      /Users/Minghao/revbayes/revbayes-development/rb`

**To Reproduce**
Using the data and script (mcmc_EFBD_mass_extinctions.Rev) from the Tutorials (https://revbayes.github.io/tutorials/divrate/efbdp_me.html), and setting up a checkpoint, an error is prompted. When the part of the model related to mass extinction is removed (mcmc_EFBD.Rev), it runs normally. Therefore, I suspect the error may be related to mass extinction.

[ME_checkpoint_bug.zip](https://github.com/revbayes/revbayes/files/14430957/ME_checkpoint_bug.zip)

**Screenshots**
<img width="1116" alt="image" src="https://github.com/revbayes/revbayes/assets/51898298/7d793063-8434-4b21-880b-da7625ceee06">

**Computer info**
I am using a Mac, and the version of RevBayes I am using is development (rapture-2377-ga37213).

**Comment by bjoelle** [comment] 2024-02-27 17:05
I can't reproduce the issue, but I get a different problem where the values of the mass extinction probabilities are not restored properly from checkpoint - I am wondering if this is tied to issue #339

**Comment by mhDu** [comment] 2024-02-28 08:35
Hi Joëlle, I'm sorry that the **_To Reproduce_** files I provided earlier was not detailed enough. I have re-uploaded the files and also provided the output file of the checkpoint, hoping that this time you can reproduce the issue.

**Comment by bjoelle** [comment] 2024-02-28 14:02
can you check if the fix in branch [memory_leak](https://github.com/revbayes/revbayes/tree/memory_leak) solves this issue ?

**Comment by mhDu** [comment] 2024-02-28 15:26
Hi Joëlle, I've checked the fix in the _**memory_leak**_ branch, and it solves the issue. Thank you for your help!

**Comment by bjoelle** [comment] 2024-02-29 07:51
Fixed by PR #430

**Closed by bjoelle** 2024-02-29 07:51 UTC
