### ISSUE TITLE
[BUG] Mixture model weights not estimated correctly

### ISSUE THREAD

**Issue by jembrown** [revbayes/revbayes#436] opened 2024-03-23 19:43 UTC
**Describe the bug**

I am attempting to estimate two sets of state frequencies associated with sites in an alignment using a profile mixture model. To do this, I'm passing a vector of two Q matrices to `dnPhyloCTMC` as the `Q` argument and a vector of two weights (with a `dnDirichlet` prior) as the `siteMatrices` argument. While the two sets of state frequencies are accurately estimated in the Q matrices, the weights just sample from the prior (i.e., the MCMC samples uniformly between 0 and 1).

**To Reproduce**

I am attaching a simulated dataset (`simData.fa`) of 113 taxa where ~90% of sites have a very strong bias towards A and C, and ~10% of sites have a very strong bias towards G and T. I have also attached the tree used to simulate the data. Both the nucleotide frequencies and mixture weights are easily and correctly estimated by other software (e.g., Bali-Phy). The script used to set up the profile mixture model is also attached (`Profile_mixture.rev`).

**Expected behavior**

The mixture weights (`mix[1]` and `mix[2]`) should be correctly estimated as ~10% and ~90%.

**Computer info**

I've observed this behavior while running RevBayes on Mac OS 14.3, using both the currently released version (1.2.1), as well as a version compiled from the `development` branch (v 1.2.2) on 3/21/24.

**Additional context**

(1) This problem may be related to some other issue with the structure of the DAG. Lines 28-29 in the script (`pi_1 := pi[1]` and `pi_2 := pi[2]`) don't seem like they should be necessary, but if they're removed the `pi` values are not written to the file specified by the model monitor.

(2) @bredelings looked into this a bit and has suggested that the problem has to do with a touch not propagating as it should through the DAG. Forcing RevBayes to recalculate conditional likelihoods for all nodes seems to fix the estimation problem.

Files available here: [mixtureBug.zip](https://github.com/revbayes/revbayes/files/14733416/mixtureBug.zip)

**Comment by jsigao** [comment] 2024-03-25 09:31
This seems to be a bug introduced in this [line](https://github.com/revbayes/revbayes/blob/master/src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h#L4080), which was part of a commit made by me attempting to avoid some of the redundant computations in the pruning. This is apparently inconsistent with the way we decide when the weighted sum of the partials needs to be recomputed [here](https://github.com/revbayes/revbayes/blob/master/src/core/distributions/phylogenetics/substitution/AbstractPhyloCTMCSiteHomogeneous.h#L914). That is, the sum is currently only recomputed when the root node is dirty, so unfortunately the sum wouldn't be updated when the site mixture probability is the only parameter affected at an MCMC step (as the partials are not changed at all and thus no node is "dirty" in that case). I apologize for this serious issue caused by my commit. I'll submit a pull request as soon as possible to fix this issue, but I'd like to post this quick message here to avoid further wasting other people's time @hoehna .

**Comment by hoehna** [comment] 2024-03-25 09:36
Thanks for the explanation and looking into this J.

**Comment by bredelings** [comment] 2024-03-25 14:42
Thanks @jsigao!

So, the simple fix is to revert that change in `AbstractPhyloCTMCSiteHomogeneous.h`.  But I wonder if it would be possible to instead ensure that the likelihood is recomputed.

1. One idea would be to mark the root node dirty in `AbstractPhyloCTMCSiteHomogeneous.h`, just to trigger the recomputation of the likelihood.  This should work, but is wasting a little bit of computation, maybe.
2. Another idea would be to move the line `this->lnProb = sumRootLikelihood();` outside the block for `if ( dirty_nodes[root_index] == true )`

Is seems that the only the computation of the root node conditional likelihoods should be inside the conditional `if ( dirty_nodes[root_index] == true )`.  The computation of the likelihood from the conditional likelihoods at the root should be done even if the root node is not dirty.

Also, at a higher level it seems odd that we would set `needs_probability_recalculation = true` and then refuse to change the likelihood.  Are there any situations where the likelihood is touched, but the likelihood is completely unchanged?  @hoehna

**Comment by jsigao** [comment] 2024-03-25 18:50
Thanks @bredelings for the suggestions!

I was also leaning towards the option 2 here as you described. While I was trying to figure out what exactly was the bug yesterday, I created a separate flag `mixture_probs_dirty` and set it to `true` when `(affecter == site_rates_probs || affecter == site_matrix_probs) `, and added an `else if ( mixture_probs_dirty == true ) this->lnProb = sumRootLikelihood(); ` after the block for `if ( dirty_nodes[root_index] == true )` (while keeping everything inside the block as is). This appeared to fix the bug (and produced identical output as option 1).

**Comment by jembrown** [comment] 2024-03-27 05:29
Thanks, @jsigao and @bredelings for looking into this so quickly!

**Comment by bredelings** [comment] 2024-04-01 13:36
Fixed by #437

**Closed by bredelings** 2024-04-01 13:36 UTC
