### ISSUE TITLE
[BUG] readPoMoCountFile does not load data

### ISSUE THREAD

**Issue by seidels** [revbayes/revbayes#563] opened 2024-10-10 08:29 UTC
**Bug description**
I am unable to load data from a count file using the readPoMoCountFile function in RevBayes v1.2.4. The function does not raise an error, but the data object is not created. The issue occurs with both the [provided tutorial data ](https://revbayes.github.io/tutorials/pomos/) and a custom count file.

**To Reproduce**
I have been following the PoMo tutorial and used the following command:

`data <- readPoMoCountFile(file="data/great_apes_1000.cf", virtualPopulationSize=12, numStates=4)
`

Console output:
_POSITION: 41275799
State: 6,0,0,0
stringvalue: 6,0,0,0
1 1e-08 1e-08 1e-08 3.34898e-07 2.14335e-05 0.000244141 0.00137174 ...
std::bad_alloc_

Even though the function does not call an error - when I check the data object, it seems not to have been assigned.
`data`
Console output:
_Missing Variable: Variable data does not exist_

To make sure that this is not a problem of the provided count file, I created my own little count file for testing, that is much shorter [my_toy_example.txt](https://github.com/user-attachments/files/17324874/my_toy_example.txt):

`data <- readPoMoCountFile(file="data/my_toy_example.txt", virtualPopulationSize=3, numStates=4)
`
Again, the data object is not created:

_POSITION: 1
State: 6,0,0,0
stringvalue: 6,0,0,0
1 1e-08 1e-08 1e-08 0.00137174 0.0877915 0.00137174 0.0877915 0.00137174 0.0877915 1e-08 1e-08 1e-08 1e-08 1e-08 1e-08  
   std::bad_alloc_

`data`
 _Missing Variable: Variable data does not exist_

To verify that this isn't an installation issue, I tested loading data using the readDiscreteCharacterData function in the [substitution model tutorial](https://revbayes.github.io/tutorials/ctmc/), and it worked as expected:
`data <- readDiscreteCharacterData("data/primates_and_galeopterus_cytb.nex")
`
_Successfully read one character matrix from file 'data/primates_and_galeopterus_cytb.nex'_ 

**Computer info**
I am using MacOS Sonoma, version 14.6.1 and revBayes v.1.2.4.

**Comment by seidels** [comment] 2024-10-10 12:41
That works! Following the tutorial, I get another error when calling the PoMo substitution model function:
```
# rate matrix
Q := fnReversiblePoMo4N(N,pi,rho,phi)
```
Error:	No function named 'fnReversiblePoMo4N'

I then tried to see which other functions are available by checking for documentation:
```
> ?fnPoMo4N
   Help is not available for "fnPoMo4N"
> ?fnPoMo2N
   Help is not available for "fnPoMo2N"
```

It seems that fnPoMoKN is functional. Is that the intended way of using PoMo?

I am a bit split about how to proceed at this point. Will the tutorial be updated soon? Are the functions on the development branch sufficiently tested for me to use them? Or should I rather compile an older version of revbayes, where the old functions are still supported?

**Comment by mrborges23** [comment] 2024-10-11 09:51
@seidels, I have just updated the PoMos tutorial. Please let me know if you encounter any problems. The most significant change is that we now set the reversible mutations outside the PoMo rate matrix. You can check the available .rev code for more details.

**Comment by seidels** [comment] 2024-11-03 12:18
@mrborges23 Thanks for updating the tutorial! 

The only problem I found is when loading the data via the command:

data <- readPoMoCountFile(countFile="data/great_apes_1000.cf", virtualPopulationSize=N, format="PoMo", samplingCorrection
   
I get the error:
Error:	Argument label 'samplingCorrection' matches no untaken parameter labels.

That seems to be coming from the argument name, that is twice "format".  
<img width="740" alt="image" src="https://github.com/user-attachments/assets/259fb122-5d74-4c9e-bf61-e77534675308">

However, I can just work around it using positional argument calling: 
data <- readPoMoCountFile(countFile="data/great_apes_1000.cf", virtualPopulationSize=N, "PoMo", "Fixed")

**Comment by davidcerny** [comment] 2024-11-03 17:49
Hi @seidels, it looks like you're not using the most recent version of the `dev_PoMo_SNP` branch (commit [f01370a](https://github.com/revbayes/revbayes/commit/f01370a128f02a471fa9698e115b95a584c6318a)). As of that commit, I get no further errors when trying to run the tutorial, nor are there any duplicated argument names:

<img width="887" alt="Screenshot 2024-11-03 at 11 47 44" src="https://github.com/user-attachments/assets/05f3deee-8a2c-4836-930e-5feed55ebd60">

**Comment by davidcerny** [comment] 2024-11-06 02:48
Since no further issues have been reported, closing this (and marking it as a duplicate of #546).

**Closed by davidcerny** 2024-11-06 02:48 UTC
Labels: duplicate
