### ISSUE TITLE
[BUG] MCMC stopping rules not working

### ISSUE THREAD

**Issue by davidcerny** [revbayes/revbayes#422] opened 2024-01-08 19:28 UTC
**Describe the bug**
MCMC stopping rules don't seem to be used too often in real-world RevBayes analyses, but they can be very useful sometimes. Pretty much the only example of their use I could find comes from [this presentation](https://applibugs.mathnum.inrae.fr/sites/default/files/2021-07/fichier-document/applibugs.18_06_21.bboussau.pdf) by @Boussau. I packaged the code given on slides 31–33 into a Rev script, made two cosmetic changes to make it work with the current version of RevBayes (renaming the second argument of `dnBinomial()` from `n` to `size`, and indexing the move vector starting from 1 rather than from 0), and tried running it. However, I encountered the following error:

```
   Error:	Argument or label mismatch for function call.
   Provided call:
   run (StoppingRule[] )
   
   Correct usage is:
   run (Natural<any> generations,
        StoppingRule[]<any> rules,
        Natural<any> tuningInterval,
        String<any> checkpointFile,
        Natural<any> checkpointInterval,
        Bool<any> underPrior)
   
   Error:	Problem processing line 46 in file "/Users/David/Downloads/stopping_rule_test.Rev"
```

Some experimentation showed that if I also supply a number of generations (i.e., if the call is of the form `run (Natural generations, StoppingRule[] rules)`), the script will run, but the stopping rules will simply be ignored.

**To reproduce**
[Here](https://github.com/revbayes/revbayes/files/13865465/stopping_rule_test.txt) is the script with Bastien's code.

**Expected behavior**
The call to the `.run()` method should start an MCMC simulation that stops when one of the six defined stopping conditions is met.

**Computer info**
macOS 12.7.1, RevBayes 1.2.2, `development` branch, commit rapture-2367-ga4a40a (one PR behind the tip of the branch).

**Comment by bjoelle** [comment] 2024-04-04 13:40
so I confirm that `generations` is a required argument for the `run` function, that seems to be as designed
generations gets converted to a stopping rule under the hood, so maybe it would make sense to require generations **or** at least one stopping rule ?
the ignoring of the rules when `generations` is provided is due to a bug I think, I will PR a fix

**Comment by bjoelle** [comment] 2024-04-04 14:01
ok it doesn't seem like a bug - RevBayes will stop when convergence is reached (as defined by the rules) **OR** when the maximum number of generations is reached **OR** when the maximum time is reached
so basically the max iterations or max time set have priority over any convergence rule, which seems like intended behaviour

**Comment by bjoelle** [comment] 2024-04-04 14:03
overall this seems like it needs documentation not fixing - @davidcerny would you agree ?

**Comment by davidcerny** [comment] 2024-04-04 17:08
Hmm, I'm not sure I would agree that the current behavior is fine and just needs to be properly documented.

First, I don't think it makes sense to have `generations` be a required argument if the stopping rule vector already contains `srMaxIteration`, since these two are clearly redundant with respect to each other. In fact, I'd go further and argue that as long as at least one other stopping rule is provided, a `.run()` call should be valid even if _neither_ `generations` nor `stMaxIteration` is specified.

Second, I think what you're saying is that the priority assigned to the individual stopping rules is determined by their placement in the vector, which is indeed what I've found now that I've played with the script some more. For example,

```
stopping_rules[1] = srMinESS(20, myOutputFile, 10000)
stopping_rules[2] = srMaxTime(50, "seconds")
```

will allow the analysis continue beyond the 50-second mark if the target ESS value has not been reached, while doing it the other way around:

```
stopping_rules[1] = srMaxTime(50, "seconds")
stopping_rules[2] = srMinESS(20, myOutputFile, 10000)
```

will kill it after 50 seconds regardless of the ESS value reached. (Incidentally, the fact that I have trouble reaching an ESS of 20 even after 1 million generations with a model as trivial as this one makes me wonder if something is broken in `srMinESS` too, but that's an unrelated question.)

To me, the ideal behavior would be "stop when at least one rule is satisfied, whichever is reached first", in which case the order in which the rules are listed wouldn't matter. I guess the current behavior would be okay too if it was properly implemented and properly documented, but I don't think either is the case.

**Comment by davidcerny** [comment] 2024-04-04 17:45
Actually, thinking about this further, the concept of "priority" doesn't really make sense when applied to stopping rules, which either get or don't get triggered – and that's it. What RevBayes currently seems to be doing is (1) stop the analysis after the specified number of `generations`, unless (2) the first element of the `stopping_rules` vector is satisfied first, in which case the analysis may stop earlier than that. I.e., there's no point in creating a `stopping_rules` vector in the first place, since all of its elements other than the first will just be ignored.

It seems to me that "stop when at least one rule is satisfied, whichever is reached first" is the only defensible choice, and the current implementation is incorrect.

**Comment by bjoelle** [comment] 2024-04-05 06:36
OK so for the first point, I will check if we can make it so that either generations or rules have to be provided but not both

For the second point I thought this was already the behaviour in place (i.e. stop when any rule is reached). I did not notice that changing the order of the rules mattered, and I think you are right that this is not intended so I will look into this further

Thanks for the feedback :)

**Comment by bjoelle** [comment] 2024-04-09 09:15
ok so it seems that the intended behaviour is to end when 1) all convergence rules are fulfilled **OR** 2) at least one of the stopping rules (max time or max gen) is fulfilled
right now this is bugged because if one rule fails to converge it never checks the following including the stopping rules (which is what leads to the issue with the rules order)
but I'm not sure the intended behaviour is correct - at the very least it is not consistent since stopping rules operate on an **OR** basis and convergence rules on an **AND** basis
=> should we switch to **OR** for everything ? should it be parametrizable by the user ? (e.g. with an added argument to stopping rules that defines whether this is an "OR" or an "AND")
@davidcerny @hoehna opinions ?

**Comment by bjoelle** [comment] 2024-04-09 09:35
Regarding the ESS rule, I couldn't identify anything wrong with it
the issue in your test is that the prior never changes (because all your priors are uniform) so the ESS of the prior is always dreadful
it's an interesting failure case but I'm not sure how/whether to fix it

**Comment by bjoelle** [comment] 2024-04-09 09:38
my current fixes are in branch `stopping_rules` if you want to run further tests

**Comment by davidcerny** [comment] 2024-04-11 17:55
Sorry for the late reply Joëlle, and thank you so much for taking the time to look into this further! I'll play around with your new branch tomorrow or this coming Saturday

**Comment by bjoelle** [comment] 2024-04-26 11:05
the bugs identified in this issue should have been resolved by the PR
@davidcerny please reopen if there are still issues which should be addressed

**Closed by bjoelle** 2024-04-26 11:05 UTC

**Comment by davidcerny** [comment] 2024-04-26 13:44
So sorry for stalling on this @bjoelle. I'm still intending to thoroughly test the current behavior, but I'll probably only get around to it after my defense next week.
