### ISSUE TITLE
[Help Wanted] error of BDS model analyses

### ISSUE THREAD

**Issue by ChaoShenzjs** [revbayes/revbayes#420] opened 2023-12-21 08:37 UTC
**Describe the desired behavior.**
I can successfully run BDS analyses using exampled tree data and scripts. Then I just replaced the input tree with my own. My tree file can be read but troubled with the error
 "Error:	Tree has serially sampled tips, but no serial sampling rate was provided.  
   Error:	Problem processing line 108 in file "mcmc_BDS.Rev""
I did not change the parameters of "NUM_TOTAL_SPECIES     = 367, NUM_RATE_CATEGORIES   = 6, H = 0.587405".
Moreover, I received the same with EBD process using my tree.

**Computer info**
RevBayes version (1.2.1) on Mac OS Apple M1

**Additional context**
My tree has 201 tips and is a representative sampling of a large lineage of about 20000 species.

Chao

**Comment by davidcerny** [comment] 2024-01-02 22:20
Hi Chao,

Is your tree supposed to include extant tips only? If so, what might have happened is that your tree exhibited small deviations from ultrametricity (i.e., its root-to-tip paths were almost but not perfectly equal in length), which RevBayes interpreted as genuine tip age differences. A tree in which different tips have different ages would then indeed have to be analyzed using a different variant of the birth-death model that accounts for serial sampling.

Assuming that this is the case, you might want to try out this solution from Liam Revell's blog and make your tree strictly ultrametric: http://blog.phytools.org/2017/03/forceultrametric-method-for-ultrametric.html

Also, if your 201-tip tree is representative "of a large lineage of about 20000 species", then you should change `NUM_TOTAL_SPECIES` from 367 to 20000, I would think.

**Comment by davidcerny** [comment] 2024-01-29 22:46
After further communication with @ChaoShenzjs via email, this problem indeed turned out to be caused by the input tree very slightly deviating from ultrametricity. Closing the issue.

**Closed by davidcerny** 2024-01-29 22:46 UTC
