### ISSUE TITLE
[BUG] Timetree object functions not working

### ISSUE THREAD

**Issue by travispark** [revbayes/revbayes#260] opened 2022-08-11 19:56 UTC
Functions within the timetree object are not working. Example error messages: 
'Error: No function named 'taxa', 
'Error: No function named 'rootAge' 

Code used:
# read in pinniped metatree file
sealtree <- readTrees("Data/mcc.tre")
# assign a variable with the taxon names from the tree, which will be used when running the bd model
taxa <- sealtree.taxa()
rootage <- sealtree.rootAge()
Functions should be returning taxa and root ages from the tree.

**Computer info**
Windows 10 64 bit, using RevBayes version 1.1.0

**Comment by davidcerny** [comment] 2022-08-15 01:36
This is a duplicate of issue #239 – in your code, `sealtree` is a *vector* of trees, and tree-related functions like `.taxa()` or `.rootAge()` can only be applied to its individual elements. Using `sealtree <- readTrees("Data/mcc.tre")[1]` will give you the expected output.

**Closed by davidcerny** 2022-08-15 01:36 UTC
